server:
  port: 9080
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: haha
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.17.40.234:3306/canal1
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml